// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WondeModels;
//
//    var wondeAttendanceCodes = WondeAttendanceCodes.FromJson(jsonString);

namespace WondeModels
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class WondeAttendanceCodes
    {
        [JsonProperty("data")]
        public List<WondeAttendanceCodes_Datum> data { get; set; }
    }

    public partial class WondeAttendanceCodes_Datum
    {
        [JsonProperty("id")]
        public string id { get; set; }

        [JsonProperty("code")]
        public string code { get; set; }

        [JsonProperty("description")]
        public string description { get; set; }

        [JsonProperty("type")]
        public string type { get; set; }

        [JsonProperty("parent_code")]
        public string parent_code { get; set; }

        [JsonProperty("government_code")]
        public string government_code { get; set; }
    }

    public partial class WondeAttendanceCodes
    {
        public static WondeAttendanceCodes FromJson(string json) => JsonConvert.DeserializeObject<WondeAttendanceCodes>(json, WondeModels.WondeAttendanceCodes_Converter.Settings);
    }

    public static class WondeAttendanceCodes_Serialize
    {
        public static string ToJson(this WondeAttendanceCodes self) => JsonConvert.SerializeObject(self, WondeModels.WondeAttendanceCodes_Converter.Settings);
    }

    internal static class WondeAttendanceCodes_Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
