// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WondeModels;
//
//    var WondeAttendanceSession = WondeAttendanceSession.FromJson(jsonString);

namespace WondeModels
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class WondeAttendanceSession
    {
        [JsonProperty("data")]
        public List<WondeAttendanceSession_Datum> data { get; set; }

        [JsonProperty("meta")]
        public WondeAttendanceSession_Meta meta { get; set; }
    }

    public partial class WondeAttendanceSession_Datum
    {
        [JsonProperty("id")]
        public string id { get; set; }

        [JsonProperty("date")]
        public WondeAttendanceSession_Date date { get; set; }

        [JsonProperty("comment")]
        public string comment { get; set; }

        [JsonProperty("session")]
        public string session { get; set; }

        [JsonProperty("employee")]
        public string employee { get; set; }

        [JsonProperty("attendance_code")]
        public string attendance_code { get; set; }

        [JsonProperty("student")]
        public string student { get; set; }
    }

    public partial class WondeAttendanceSession_Date
    {
        [JsonProperty("date")]
        public DateTime date { get; set; }

        [JsonProperty("timezone_type")]
        public long timezone_type { get; set; }

        [JsonProperty("timezone")]
        public string timezone { get; set; }
    }

    public partial class WondeAttendanceSession_Meta
    {
        [JsonProperty("pagination")]
        public WondeAttendanceSession_Pagination pagination { get; set; }

        [JsonProperty("includes")]
        public List<object> includes { get; set; }
    }

    public partial class WondeAttendanceSession_Pagination
    {
        [JsonProperty("next")]
        public Uri next { get; set; }

        [JsonProperty("previous")]
        public object previous { get; set; }

        [JsonProperty("more")]
        public bool more { get; set; }

        [JsonProperty("per_page")]
        public long per_page { get; set; }

        [JsonProperty("current_page")]
        public long current_page { get; set; }
    }

    public partial class WondeAttendanceSession
    {
        public static WondeAttendanceSession FromJson(string json) => JsonConvert.DeserializeObject<WondeAttendanceSession>(json, WondeModels.WondeAttendanceSession_Converter.Settings);
    }

    public static class WondeAttendanceSession_Serialize
    {
        public static string ToJson(this WondeAttendanceSession self) => JsonConvert.SerializeObject(self, WondeModels.WondeAttendanceSession_Converter.Settings);
    }

    internal static class WondeAttendanceSession_Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
