// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WondeModels;
//
//    var wondeSchool = WondeSchool.FromJson(jsonString);

namespace WondeModels
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class WondeSchool
    {
        [JsonProperty("data")]
        public List<WondeSchool_Datum> data { get; set; }

        [JsonProperty("meta")]
        public WondeSchool_Meta meta { get; set; }
    }

    public partial class WondeSchool_Datum
    {
        [JsonProperty("id")]
        public string id { get; set; }

        [JsonProperty("name")]
        public string name { get; set; }

        [JsonProperty("establishment_number")]
        public string establishment_number { get; set; }

        [JsonProperty("urn")]
        public long urn { get; set; }

        [JsonProperty("phase_of_education")]
        public string phase_of_education { get; set; }

        [JsonProperty("la_code")]
        public string la_code { get; set; }

        [JsonProperty("timezone")]
        public string timezone { get; set; }

        [JsonProperty("mis")]
        public string mis { get; set; }

        [JsonProperty("address")]
        public WondeSchool_Address address { get; set; }

        [JsonProperty("extended")]
        public WondeSchool_Extended extended { get; set; }

        [JsonProperty("region")]
        public WondeSchool_Region region { get; set; }
    }

    public partial class WondeSchool_Address
    {
        [JsonProperty("address_line_1")]
        public string address_line_1 { get; set; }

        [JsonProperty("address_line_2")]
        public string address_line_2 { get; set; }

        [JsonProperty("address_town")]
        public string address_town { get; set; }

        [JsonProperty("address_postcode")]
        public string address_postcode { get; set; }

        [JsonProperty("address_country")]
        public WondeSchool_AddressCountry address_country { get; set; }
    }

    public partial class WondeSchool_AddressCountry
    {
        [JsonProperty("code")]
        public string code { get; set; }

        [JsonProperty("name")]
        public string name { get; set; }

        [JsonProperty("iso_3166_2")]
        public string iso_3166_2 { get; set; }
    }

    public partial class WondeSchool_Extended
    {
        [JsonProperty("allows_writeback")]
        public bool allows_writeback { get; set; }

        [JsonProperty("has_timetables")]
        public bool has_timetables { get; set; }

        [JsonProperty("has_lesson_attendance")]
        public bool has_lesson_attendance { get; set; }

        [JsonProperty("wonde_client_version")]
        public string wonde_client_version { get; set; }

        [JsonProperty("audit_approved_at")]
        public WondeSchool_AuditApprovedAt audit_approved_at { get; set; }
    }

    public partial class WondeSchool_AuditApprovedAt
    {
        [JsonProperty("date")]
        public DateTimeOffset date { get; set; }

        [JsonProperty("timezone_type")]
        public long timezone_type { get; set; }

        [JsonProperty("timezone")]
        public string timezone { get; set; }
    }

    public partial class WondeSchool_Region
    {
        [JsonProperty("code")]
        public string code { get; set; }

        [JsonProperty("domain")]
        public string domain { get; set; }

        [JsonProperty("school_url")]
        public Uri school_url { get; set; }

        [JsonProperty("identifiers")]
        public WondeSchool_Identifiers identifiers { get; set; }
    }

    public partial class WondeSchool_Identifiers
    {
        [JsonProperty("la_code")]
        public string la_code { get; set; }

        [JsonProperty("establishment_number")]
        public string establishment_number { get; set; }

        [JsonProperty("urn")]
        public long urn { get; set; }
    }

    public partial class WondeSchool_Meta
    {
        [JsonProperty("pagination")]
        public WondeSchool_Pagination pagination { get; set; }

        [JsonProperty("includes")]
        public List<string> includes { get; set; }
    }

    public partial class WondeSchool_Pagination
    {
        [JsonProperty("next")]
        public object next { get; set; }

        [JsonProperty("previous")]
        public object previous { get; set; }

        [JsonProperty("more")]
        public bool more { get; set; }

        [JsonProperty("per_page")]
        public long per_page { get; set; }

        [JsonProperty("current_page")]
        public long current_page { get; set; }
    }

    public partial class WondeSchool
    {
        public static WondeSchool FromJson(string json) => JsonConvert.DeserializeObject<WondeSchool>(json, WondeModels.WondeSchool_Converter.Settings);
    }

    public static class WondeSchool_Serialize
    {
        public static string ToJson(this WondeSchool self) => JsonConvert.SerializeObject(self, WondeModels.WondeSchool_Converter.Settings);
    }

    internal static class WondeSchool_Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
