// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WondeModels;
//
//    var wondePhoto = WondePhoto.FromJson(jsonString);

namespace WondeModels
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class WondePhoto
    {
        [JsonProperty("data")]
        public List<WondePhoto_Datum> data { get; set; }

        [JsonProperty("meta")]
        public WondePhoto_Meta meta { get; set; }
    }

    public partial class WondePhoto_Datum
    {
        [JsonProperty("id")]
        public string id { get; set; }

        [JsonProperty("content")]
        public string content { get; set; }

        [JsonProperty("person_id")]
        public string person_id { get; set; }

        [JsonProperty("person_mis_id")]
        public string person_mis_id { get; set; }

        [JsonProperty("person_type")]
        public string person_type { get; set; }

        [JsonProperty("created_at")]
        public WondePhoto_Date created_at { get; set; }

        [JsonProperty("updated_at")]
        public WondePhoto_Date updated_at { get; set; }
    }

    public partial class WondePhoto_Date
    {
        [JsonProperty("date")]
        public DateTime date { get; set; }

        [JsonProperty("timezone_type")]
        public long timezone_type { get; set; }

        [JsonProperty("timezone")]
        public string timezone { get; set; }
    }

    public partial class WondePhoto_Meta
    {
        [JsonProperty("pagination")]
        public WondePhoto_Pagination pagination { get; set; }

        [JsonProperty("includes")]
        public List<object> includes { get; set; }
    }

    public partial class WondePhoto_Pagination
    {
        [JsonProperty("next")]
        public Uri next { get; set; }

        [JsonProperty("previous")]
        public object previous { get; set; }

        [JsonProperty("more")]
        public bool more { get; set; }

        [JsonProperty("per_page")]
        public long per_page { get; set; }

        [JsonProperty("current_page")]
        public long current_page { get; set; }
    }

    public partial class WondePhoto
    {
        public static WondePhoto FromJson(string json) => JsonConvert.DeserializeObject<WondePhoto>(json, WondeModels.WondePhoto_Converter.Settings);
    }

    public static class WondePhoto_Serialize
    {
        public static string ToJson(this WondePhoto self) => JsonConvert.SerializeObject(self, WondeModels.WondePhoto_Converter.Settings);
    }

    internal static class WondePhoto_Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
