// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WondeModels;
//
//    var wondeSubject = WondeSubject.FromJson(jsonString);

namespace WondeModels
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class WondeSubject
    {
        [JsonProperty("data")]
        public List<WondeSubject_Datum> data { get; set; }

        [JsonProperty("meta")]
        public WondeSubject_Meta meta { get; set; }
    }

    public partial class WondeSubject_Datum
    {
        [JsonProperty("id")]
        public string id { get; set; }

        [JsonProperty("mis_id")]
        public string mis_id { get; set; }

        [JsonProperty("code")]
        public string code { get; set; }

        [JsonProperty("name")]
        public string name { get; set; }

        [JsonProperty("active")]
        public bool? active { get; set; }

        [JsonProperty("created_at")]
        public WondeSubject_Date created_at { get; set; }

        [JsonProperty("updated_at")]
        public WondeSubject_Date updated_at { get; set; }
    }

    public partial class WondeSubject_Date
    {
        [JsonProperty("date")]
        public DateTime date { get; set; }

        [JsonProperty("timezone_type")]
        public long timezone_type { get; set; }

        [JsonProperty("timezone")]
        public string timezone { get; set; }
    }

    public partial class WondeSubject_Meta
    {
        [JsonProperty("pagination")]
        public WondeSubject_Pagination pagination { get; set; }

        [JsonProperty("includes")]
        public List<string> includes { get; set; }
    }

    public partial class WondeSubject_Pagination
    {
        [JsonProperty("next")]
        public Uri next { get; set; }

        [JsonProperty("previous")]
        public Uri previous { get; set; }

        [JsonProperty("more")]
        public bool more { get; set; }

        [JsonProperty("per_page")]
        public long per_page { get; set; }

        [JsonProperty("current_page")]
        public long current_page { get; set; }
    }

    public partial class WondeSubject
    {
        public static WondeSubject FromJson(string json) => JsonConvert.DeserializeObject<WondeSubject>(json, WondeModels.WondeSubject_Converter.Settings);
    }

    public static class WondeSubject_Serialize
    {
        public static string ToJson(this WondeSubject self) => JsonConvert.SerializeObject(self, WondeModels.WondeSubject_Converter.Settings);
    }

    internal static class WondeSubject_Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
