// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WondeModels;
//
//    var wondeClasses = WondeClasses.FromJson(jsonString);

namespace WondeModels
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class WondeClasses
    {
        [JsonProperty("data")]
        public List<WondeClassesDatum> data { get; set; }

        [JsonProperty("meta")]
        public WondeClassesMeta meta { get; set; }
    }

    public partial class WondeClassesDatum
    {
        [JsonProperty("id")]
        public string id { get; set; }

        [JsonProperty("mis_id")]
        public string mis_id { get; set; }

        [JsonProperty("name")]
        public string name { get; set; }

        [JsonProperty("code")]
        public object code { get; set; }

        [JsonProperty("description")]
        public string description { get; set; }

        [JsonProperty("subject")]
        public string subject { get; set; }

        [JsonProperty("alternative")]
        public bool? alternative { get; set; }

        [JsonProperty("priority")]
        public object priority { get; set; }

        [JsonProperty("academic_year")]
        public string academic_year { get; set; }

        [JsonProperty("year_group")]
        public string year_group { get; set; }

        [JsonProperty("restored_at")]
        public object restored_at { get; set; }

        [JsonProperty("created_at")]
        public WondeClasses_CreatedAt created_at { get; set; }

        [JsonProperty("updated_at")]
        public WondeClasses_CreatedAt updated_at { get; set; }

        [JsonProperty("meta")]
        public object meta { get; set; }

        [JsonProperty("employees")]
        public WondeClasses_Employees employees { get; set; }

        [JsonProperty("students")]
        public WondeStudent students { get; set; }
    }

    public partial class WondeClasses_CreatedAt
    {
        [JsonProperty("date")]
        public DateTime date { get; set; }

        [JsonProperty("timezone_type")]
        public long timezone_type { get; set; }

        [JsonProperty("timezone")]
        public string timezone { get; set; }
    }

    public partial class WondeClasses_Employees
    {
        [JsonProperty("data")]
        public List<WondeClasses_EmployeesDatum> data { get; set; }
    }

    public partial class WondeClasses_EmployeesDatum
    {
        [JsonProperty("id")]
        public string id { get; set; }

        [JsonProperty("upi")]
        public string upi { get; set; }

        [JsonProperty("mis_id")]
        public string mis_id { get; set; }

        [JsonProperty("initials")]
        public string initials { get; set; }

        [JsonProperty("title")]
        public string title { get; set; }

        [JsonProperty("surname")]
        public string surname { get; set; }

        [JsonProperty("forename")]
        public string forename { get; set; }

        [JsonProperty("middle_names")]
        public string middle_names { get; set; }

        [JsonProperty("legal_surname")]
        public string legal_surname { get; set; }

        [JsonProperty("legal_forename")]
        public string legal_forename { get; set; }

        [JsonProperty("gender")]
        public WondeClasses_CreatedAt gender { get; set; }

        [JsonProperty("date_of_birth")]
        public WondeClasses_CreatedAt date_of_birth { get; set; }

        [JsonProperty("restored_at")]
        public WondeClasses_CreatedAt restored_at { get; set; }

        [JsonProperty("updated_at")]
        public WondeClasses_CreatedAt updated_at { get; set; }

        [JsonProperty("created_at")]
        public WondeClasses_CreatedAt created_at { get; set; }

        [JsonProperty("meta")]
        public WondeClasses_DatumMeta meta { get; set; }
    }

    public partial class WondeClasses_DatumMeta
    {
        [JsonProperty("role")]
        public string role { get; set; }

        [JsonProperty("all_roles")]
        public List<string> all_roles { get; set; }

        [JsonProperty("is_main_teacher")]
        public bool? is_main_teacher { get; set; }

        [JsonProperty("is_class_teacher")]
        public bool? is_class_teacher { get; set; }
    }

    public partial class WondeClassesMeta
    {
        [JsonProperty("pagination")]
        public WondeClasses_Pagination pagination { get; set; }

        [JsonProperty("includes")]
        public List<string> includes { get; set; }
    }

    public partial class WondeClasses_Pagination
    {
        [JsonProperty("next")]
        public Uri next { get; set; }

        [JsonProperty("previous")]
        public object previous { get; set; }

        [JsonProperty("more")]
        public bool more { get; set; }

        [JsonProperty("per_page")]
        public long per_page { get; set; }

        [JsonProperty("current_page")]
        public long current_page { get; set; }
    }

    public partial class WondeClasses
    {
        public static WondeClasses FromJson(string json) => JsonConvert.DeserializeObject<WondeClasses>(json, WondeModels.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this WondeClasses self) => JsonConvert.SerializeObject(self, WondeModels.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
