// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WondeModels;
//
//    var wondeGroups = WondeGroups.FromJson(jsonString);

namespace WondeModels
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class WondeGroups
    {
        [JsonProperty("data")]
        public List<WondeGroupsDatum> data { get; set; }

        [JsonProperty("meta")]
        public WondeGroupsMeta meta { get; set; }
    }

    public partial class WondeGroupsDatum
    {
        [JsonProperty("id")]
        public string id { get; set; }

        [JsonProperty("mis_id")]
        public string mis_id { get; set; }

        [JsonProperty("name")]
        public string name { get; set; }

        [JsonProperty("code")]
        public string code { get; set; }

        [JsonProperty("type")]
        public string type { get; set; }

        [JsonProperty("description")]
        public string description { get; set; }

        [JsonProperty("notes")]
        public string notes { get; set; }

        [JsonProperty("division")]
        public string division { get; set; }

        [JsonProperty("created_at")]
        public WondeGroups_Date created_at { get; set; }

        [JsonProperty("updated_at")]
        public WondeGroups_Date updated_at { get; set; }

        [JsonProperty("meta")]
        public WondeGroups_DatumMeta meta { get; set; }//Empty ??

        [JsonProperty("employees")]
        public WondeEmployee employees { get; set; }

        [JsonProperty("students")]
        public WondeStudent students { get; set; }
    }

    public partial class WondeGroups_Date
    {
        [JsonProperty("date")]
        public DateTime date { get; set; }

        [JsonProperty("timezone_type")]
        public long timezone_type { get; set; }

        [JsonProperty("timezone")]
        public string timezone { get; set; }
    }


    public partial class WondeGroups_DatumMeta
    {
        [JsonProperty("role")]
        public string role { get; set; }

        [JsonProperty("main")]
        public object main { get; set; }

        [JsonProperty("all_roles")]
        public List<string> all_roles { get; set; }
    }


    public partial class WondeGroupsMeta
    {
        [JsonProperty("pagination")]
        public WondeGroups_Pagination pagination { get; set; }

        [JsonProperty("includes")]
        public List<string> includes { get; set; }
    }

    public partial class WondeGroups_Pagination
    {
        [JsonProperty("next")]
        public Uri next { get; set; }

        [JsonProperty("previous")]
        public object previous { get; set; }

        [JsonProperty("more")]
        public bool more { get; set; }

        [JsonProperty("per_page")]
        public long per_page { get; set; }

        [JsonProperty("current_page")]
        public long current_page { get; set; }
    }

    public partial class WondeGroups
    {
        public static WondeGroups FromJson(string json) => JsonConvert.DeserializeObject<WondeGroups>(json, WondeModels.WondeGroups_Converter.Settings);
    }

    public static class WondeGroups_Serialize
    {
        public static string ToJson(this WondeGroups self) => JsonConvert.SerializeObject(self, WondeModels.WondeGroups_Converter.Settings);
    }

    internal static class WondeGroups_Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
