// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WondeModels;
//
//    var wondeAchievement = WondeAchievement.FromJson(jsonString);

namespace WondeModels
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class WondeAchievement
    {
        [JsonProperty("data")]
        public List<WondeAchievementDatum> data { get; set; }

        [JsonProperty("meta")]
        public WondeAchievementMeta meta { get; set; }
    }

    public partial class WondeAchievementDatum
    {
        [JsonProperty("id")]
        public string id { get; set; }

        [JsonProperty("mis_id")]
        public string mis_id { get; set; }

        [JsonProperty("type")]
        public string type { get; set; }

        [JsonProperty("action")]
        public object action { get; set; }

        [JsonProperty("class")]
        public string @class { get; set; }

        [JsonProperty("subject")]
        public string subject { get; set; }

        [JsonProperty("points")]
        public long points { get; set; }

        [JsonProperty("total_points")]
        public object total_points { get; set; }

        [JsonProperty("comment")]
        public string comment { get; set; }

        [JsonProperty("parents_notified")]
        public object parents_notified { get; set; }

        [JsonProperty("achievement_date")]
        public AchievementDate achievement_date { get; set; }

        [JsonProperty("action_date")]
        public AchievementDate action_date { get; set; }

        [JsonProperty("recorded_date")]
        public AchievementDate recorded_date { get; set; }

        [JsonProperty("created_at")]
        public AchievementDate created_at { get; set; }

        [JsonProperty("updated_at")]
        public AchievementDate updated_at { get; set; }

        [JsonProperty("students")]
        public WondeAchievementStudents students { get; set; }
    }

    public partial class AchievementDate
    {
        [JsonProperty("date")]
        public DateTimeOffset date { get; set; }

        [JsonProperty("timezone_type")]
        public long timezone_type { get; set; }

        [JsonProperty("timezone")]
        public string timezone { get; set; }
    }

    public partial class WondeAchievementStudents
    {
        [JsonProperty("data")]
        public List<WondeAchievementStudentsDatum> data { get; set; }
    }

    public partial class WondeAchievementStudentsDatum
    {
        [JsonProperty("id")]
        public string id { get; set; }

        [JsonProperty("upi")]
        public object upi { get; set; }

        [JsonProperty("mis_id")]
        public string mis_id { get; set; }

        [JsonProperty("initials")]
        public string initials { get; set; }

        [JsonProperty("title")]
        public object title { get; set; }

        [JsonProperty("surname")]
        public string surname { get; set; }

        [JsonProperty("forename")]
        public string forename { get; set; }

        [JsonProperty("middle_names")]
        public string middle_names { get; set; }

        [JsonProperty("legal_surname")]
        public string legal_surname { get; set; }

        [JsonProperty("legal_forename")]
        public string legal_forename { get; set; }

        [JsonProperty("gender")]
        public string gender { get; set; }

        [JsonProperty("gender_identity")]
        public object gender_identity { get; set; }

        [JsonProperty("date_of_birth")]
        public AchievementDate date_of_birth { get; set; }

        [JsonProperty("restored_at")]
        public AchievementDate restored_at { get; set; }

        [JsonProperty("created_at")]
        public AchievementDate created_at { get; set; }

        [JsonProperty("updated_at")]
        public AchievementDate updated_at { get; set; }

        [JsonProperty("meta")]
        public WondeAchievementDatumMeta meta { get; set; }
    }

    public partial class WondeAchievementDatumMeta
    {
        [JsonProperty("points")]
        public long points { get; set; }
    }

    public partial class WondeAchievementMeta
    {
        [JsonProperty("pagination")]
        public WondeAchievementPagination pagination { get; set; }

        [JsonProperty("includes")]
        public List<string> includes { get; set; }
    }

    public partial class WondeAchievementPagination
    {
        [JsonProperty("next")]
        public Uri next { get; set; }

        [JsonProperty("previous")]
        public object previous { get; set; }

        [JsonProperty("more")]
        public bool more { get; set; }

        [JsonProperty("per_page")]
        public long per_page { get; set; }

        [JsonProperty("current_page")]
        public long current_page { get; set; }
    }

    public partial class WondeAchievement
    {
        public static WondeAchievement FromJson(string json) => JsonConvert.DeserializeObject<WondeAchievement>(json, WondeModels.Converter.Settings);
    }

    public static class WondeAchievementSerialize
    {
        public static string ToJson(this WondeAchievement self) => JsonConvert.SerializeObject(self, WondeModels.Converter.Settings);
    }

    internal static class WondeAchievementConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
