// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WondeModels;
//
//    var wondeBehaviour = WondeBehaviour.FromJson(jsonString);

namespace WondeModels
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class WondeBehaviour
    {
        [JsonProperty("data")]
        public List<WondeBehaviourDatum> data { get; set; }

        [JsonProperty("meta")]
        public WondeBehaviourMeta meta { get; set; }
    }

    public partial class WondeBehaviourDatum
    {
        [JsonProperty("id")]
        public string id { get; set; }

        [JsonProperty("mis_id")]
        public string mis_id { get; set; }

        [JsonProperty("type")]
        public string type { get; set; }

        [JsonProperty("action")]
        public object action { get; set; }

        [JsonProperty("points")]
        public long points { get; set; }

        [JsonProperty("total_points")]
        public object total_points { get; set; }

        [JsonProperty("comment")]
        public string comment { get; set; }

        [JsonProperty("parents_notified")]
        public object parents_notified { get; set; }

        [JsonProperty("location")]
        public string location { get; set; }

        [JsonProperty("class")]
        public string @class { get; set; }

        [JsonProperty("subject")]
        public string subject { get; set; }

        [JsonProperty("status")]
        public string status { get; set; }

        [JsonProperty("incident_date")]
        public CreatedAt incident_date { get; set; }

        [JsonProperty("action_date")]
        public CreatedAt action_date { get; set; }

        [JsonProperty("bullying_type")]
        public object bullying_type { get; set; }

        [JsonProperty("recorded_date")]
        public CreatedAt recorded_date { get; set; }

        [JsonProperty("sensitivity")]
        public object sensitivity { get; set; }

        [JsonProperty("created_at")]
        public CreatedAt created_at { get; set; }

        [JsonProperty("updated_at")]
        public CreatedAt updated_at { get; set; }

        [JsonProperty("students")]
        public WondeBehaviourStudents students { get; set; }
    }

    public partial class CreatedAt
    {
        [JsonProperty("date")]
        public DateTimeOffset date { get; set; }

        [JsonProperty("timezone_type")]
        public long timezone_type { get; set; }

        [JsonProperty("timezone")]
        public string timezone { get; set; }
    }

    public partial class WondeBehaviourStudents
    {
        [JsonProperty("data")]
        public List<WondeBehaviourStudentsDatum> data { get; set; }
    }

    public partial class WondeBehaviourStudentsDatum
    {
        [JsonProperty("id")]
        public string id { get; set; }

        [JsonProperty("upi")]
        public object upi { get; set; }

        [JsonProperty("mis_id")]
        public string mis_id { get; set; }

        [JsonProperty("initials")]
        public string initials { get; set; }

        [JsonProperty("title")]
        public object title { get; set; }

        [JsonProperty("surname")]
        public string surname { get; set; }

        [JsonProperty("forename")]
        public string forename { get; set; }

        [JsonProperty("middle_names")]
        public string middle_names { get; set; }

        [JsonProperty("legal_surname")]
        public string legal_surname { get; set; }

        [JsonProperty("legal_forename")]
        public string legal_forename { get; set; }

        [JsonProperty("gender")]
        public string gender { get; set; }

        [JsonProperty("gender_identity")]
        public object gender_identity { get; set; }

        [JsonProperty("date_of_birth")]
        public CreatedAt date_of_birth { get; set; }

        [JsonProperty("restored_at")]
        public CreatedAt restored_at { get; set; }

        [JsonProperty("created_at")]
        public CreatedAt created_at { get; set; }

        [JsonProperty("updated_at")]
        public CreatedAt updated_at { get; set; }

        [JsonProperty("meta")]
        public WondeBehaviourDatumMeta meta { get; set; }
    }

    public partial class WondeBehaviourDatumMeta
    {
        [JsonProperty("role")]
        public object role { get; set; }

        [JsonProperty("action")]
        public object action { get; set; }

        [JsonProperty("points")]
        public long points { get; set; }
    }

    public partial class WondeBehaviourMeta
    {
        [JsonProperty("pagination")]
        public WondeBehaviourPagination pagination { get; set; }

        [JsonProperty("includes")]
        public List<string> includes { get; set; }
    }

    public partial class WondeBehaviourPagination
    {
        [JsonProperty("next")]
        public Uri next { get; set; }

        [JsonProperty("previous")]
        public object previous { get; set; }

        [JsonProperty("more")]
        public bool more { get; set; }

        [JsonProperty("per_page")]
        public long per_page { get; set; }

        [JsonProperty("current_page")]
        public long current_page { get; set; }
    }

    public partial class WondeBehaviour
    {
        public static WondeBehaviour FromJson(string json) => JsonConvert.DeserializeObject<WondeBehaviour>(json, WondeModels.Converter.Settings);
    }

    public static class WondeBehaviourSerialize
    {
        public static string ToJson(this WondeBehaviour self) => JsonConvert.SerializeObject(self, WondeModels.Converter.Settings);
    }

    internal static class WondeBehaviourConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
