// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WondeModels;
//
//    var wondeExclusion = WondeExclusion.FromJson(jsonString);

namespace WondeModels
{
    //using Microsoft.AspNetCore.Http.HttpResults;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System;
    using System.Collections.Generic;
    using System.Globalization;

    public partial class WondeExclusion
    {
        [JsonProperty("data")]
        public List<Datum> data { get; set; }

        [JsonProperty("meta")]
        public WondeExclusion_Meta meta { get; set; }
    }

    public partial class Datum
    {
        [JsonProperty("id")]
        public string id { get; set; }

        [JsonProperty("mis_id")]
        public string mis_id { get; set; }

        [JsonProperty("type")]
        public string type { get; set; }

        [JsonProperty("type_code")]
        public string type_code { get; set; }

        [JsonProperty("reason")]
        public string reason { get; set; }

        [JsonProperty("reason_code")]
        public string reason_code { get; set; }

        [JsonProperty("start_date")]
        public WondeExclusion_CreatedAt start_date { get; set; }

        [JsonProperty("start_session")]
        public string start_session { get; set; }

        [JsonProperty("end_date")]
        public WondeExclusion_CreatedAt end_date { get; set; }

        [JsonProperty("end_session")]
        public string end_session { get; set; }

        [JsonProperty("sessions")]
        public string sessions { get; set; }

        [JsonProperty("days")]
        public string days { get; set; }

        [JsonProperty("academic_year")]
        public string academic_year { get; set; }

        [JsonProperty("term")]
        public string term { get; set; }

        [JsonProperty("comments")]
        public string comments { get; set; }

        [JsonProperty("agencies_involved")]
        public string agencies_involved { get; set; }

        [JsonProperty("discipline_committee_date")]
        public WondeExclusion_CreatedAt discipline_committee_date { get; set; }

        [JsonProperty("discipline_committee_result")]
        public string discipline_committee_result { get; set; }

        [JsonProperty("discipline_committee_reinstatement_date")]
        public WondeExclusion_CreatedAt discipline_committee_reinstatement_date { get; set; }

        [JsonProperty("discipline_committee_representation_made")]
        public bool? discipline_committee_representation_made { get; set; }

        [JsonProperty("appeal_received")]
        public bool? appeal_received { get; set; }

        [JsonProperty("appeal_result")]
        public string appeal_result { get; set; }

        [JsonProperty("appeal_result_date")]
        public WondeExclusion_CreatedAt appeal_result_date { get; set; }

        [JsonProperty("appeal_reinstatement_date")]
        public WondeExclusion_CreatedAt appeal_reinstatement_date { get; set; }

        [JsonProperty("created_at")]
        public WondeExclusion_CreatedAt created_at { get; set; }

        [JsonProperty("updated_at")]
        public WondeExclusion_CreatedAt updated_at { get; set; }

        [JsonProperty("student-leaver", NullValueHandling = NullValueHandling.Ignore)]
        public WondeExclusion_StudentLeaver studentleaver { get; set; }

        [JsonProperty("student", NullValueHandling = NullValueHandling.Ignore)]
        public WondeExclusion_Student student { get; set; }
    }


    public partial class WondeExclusion_Student
    {
        [JsonProperty("data")]
        public WondeExclusion_StudentData data { get; set; }
    }

    public partial class WondeExclusion_StudentData
    {
        [JsonProperty("id")]
        public string id { get; set; }
    }

    public partial class WondeExclusion_StudentLeaver
    {
        [JsonProperty("data")]
        public WondeExclusion_StudentLeaverData data { get; set; }
    }

    public partial class WondeExclusion_StudentLeaverData
    {
        [JsonProperty("id")]
        public string id { get; set; }
    }



    public partial class WondeExclusion_CreatedAt
    {
        [JsonProperty("date")]
        public DateTime date { get; set; }

        [JsonProperty("timezone_type")]
        public long timezone_type { get; set; }

        [JsonProperty("timezone")]
        public string timezone { get; set; }
    }

    public partial class WondeExclusion_Meta
    {
        [JsonProperty("pagination")]
        public WondeExclusion_Pagination pagination { get; set; }

        [JsonProperty("includes")]
        public List<string> includes { get; set; }
    }

    public partial class WondeExclusion_Pagination
    {
        [JsonProperty("next")]
        public Uri next { get; set; }

        [JsonProperty("previous")]
        public object previous { get; set; }

        [JsonProperty("more")]
        public bool more { get; set; }

        [JsonProperty("per_page")]
        public long per_page { get; set; }

        [JsonProperty("current_page")]
        public long current_page { get; set; }
    }

    public partial class WondeExclusion
    {
        public static WondeExclusion FromJson(string json) => JsonConvert.DeserializeObject<WondeExclusion>(json, WondeModels.WondeExclusion_Converter.Settings);
    }

    public static class WondeExclusion_Serialize
    {
        public static string ToJson(this WondeExclusion self) => JsonConvert.SerializeObject(self, WondeModels.WondeExclusion_Converter.Settings);
    }

    internal static class WondeExclusion_Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
