// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WondeModels;
//
//    var wondeEmployee = WondeEmployee.FromJson(jsonString);

namespace WondeModels
{
    //using Microsoft.AspNetCore.Http.HttpResults;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System;
    using System.Collections.Generic;
    using System.Globalization;

    public partial class WondeEmployee
    {
        [JsonProperty("data")]
        public List<WondeEmployee_Datum> data { get; set; }

        [JsonProperty("meta")]
        public WondeEmployee_Meta meta { get; set; }
    }

    public partial class WondeEmployee_Datum
    {
        [JsonProperty("id")]
        public string id { get; set; }

        [JsonProperty("upi")]
        public string upi { get; set; }

        [JsonProperty("mis_id")]
        public string mis_id { get; set; }

        [JsonProperty("initials")]
        public string initials { get; set; }

        [JsonProperty("title")]
        public string title { get; set; }

        [JsonProperty("surname")]
        public string surname { get; set; }

        [JsonProperty("forename")]
        public string forename { get; set; }

        [JsonProperty("middle_names")]
        public string middle_names { get; set; }

        [JsonProperty("legal_surname")]
        public string legal_surname { get; set; }

        [JsonProperty("legal_forename")]
        public string legal_forename { get; set; }

        [JsonProperty("gender")]
        public string gender { get; set; }

        [JsonProperty("date_of_birth")]
        public WondeEmployee_DateObj date_of_birth { get; set; }

        [JsonProperty("restored_at")]
        public WondeEmployee_DateObj restored_at { get; set; }

        [JsonProperty("updated_at")]
        public WondeEmployee_DateObj updated_at { get; set; }

        [JsonProperty("created_at")]
        public WondeEmployee_DateObj created_at { get; set; }

        [JsonProperty("employment_details")]
        public WondeEmployee_EmploymentDetails employment_details { get; set; }

        [JsonProperty("contact_details")]
        public WondeEmployee_ContactDetails contact_details { get; set; }
    }

    public partial class WondeEmployee_EmploymentDetails
    {
        [JsonProperty("data")]
        public WondeEmployee_EmploymentDetails_data data { get; set; }
    }
    public partial class WondeEmployee_EmploymentDetails_data
    {
        [JsonProperty("teaching_staff")]
        public bool? teaching_staff { get; set; }

        [JsonProperty("current")]
        public bool? current { get; set; }

        [JsonProperty("teacher_number")]
        public string teacher_number { get; set; }

        [JsonProperty("teacher_category")]
        public string teacher_category { get; set; }

        [JsonProperty("staff_code")]
        public string staff_code { get; set; }

        [JsonProperty("primary_location")]
        public string primary_location { get; set; }

        [JsonProperty("employment_start_date")]
        public WondeEmployee_DateObj employment_start_date { get; set; }

        [JsonProperty("employment_end_date")]
        public WondeEmployee_DateObj employment_end_date { get; set; }

        [JsonProperty("local_authority_start_date")]
        public WondeEmployee_DateObj local_authority_start_date { get; set; }

        [JsonProperty("employee_payroll_number")]
        public string employee_payroll_number { get; set; }

        [JsonProperty("role_text")]
        public string role_text { get; set; }

        [JsonProperty("qualified_teacher_status")]
        public string qualified_teacher_status { get; set; }

        [JsonProperty("qualified_teacher_status_route")]
        public string qualified_teacher_status_route { get; set; }

        [JsonProperty("higher_level_teaching_assistant_status")]
        public string higher_level_teaching_assistant_status { get; set; }
    }

    public partial class WondeEmployee_ContactDetails
    {
        [JsonProperty("data")]
        public WondeEmployee_ContactDetails_Data data { get; set; }
    }

    public partial class WondeEmployee_ContactDetails_Data
    {

        [JsonProperty("emails")]
        public Emails emails { get; set; }
    }

    public partial class Emails
    {
        [JsonProperty("email")]
        public string email { get; set; }

        [JsonProperty("primary")]
        public string primary { get; set; }

        [JsonProperty("home")]
        public string home { get; set; }

        [JsonProperty("work")]
        public string work { get; set; }
    }
    public partial class WondeEmployee_DateObj
    {
        [JsonProperty("date")]
        public DateTime date { get; set; }

        [JsonProperty("timezone_type")]
        public long timezone_type { get; set; }

        [JsonProperty("timezone")]
        public string timezone { get; set; }
    }

    public partial class WondeEmployee_Meta
    {
        [JsonProperty("pagination")]
        public WondeEmployee_Pagination pagination { get; set; }

        [JsonProperty("includes")]
        public List<string> includes { get; set; }
    }

    public partial class WondeEmployee_Pagination
    {
        [JsonProperty("next")]
        public Uri next { get; set; }

        [JsonProperty("previous")]
        public object previous { get; set; }

        [JsonProperty("more")]
        public bool more { get; set; }

        [JsonProperty("per_page")]
        public long per_page { get; set; }

        [JsonProperty("current_page")]
        public long current_page { get; set; }
    }

    public partial class WondeEmployee
    {
        public static WondeEmployee FromJson(string json) => JsonConvert.DeserializeObject<WondeEmployee>(json, WondeModels.WondeEmployee_Converter.Settings);
    }

    public static class WondeEmployee_Serialize
    {
        public static string ToJson(this WondeEmployee self) => JsonConvert.SerializeObject(self, WondeModels.WondeEmployee_Converter.Settings);
    }

    internal static class WondeEmployee_Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
