// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WondeModels;
//
//    var wondeStudent = WondeStudent.FromJson(jsonString);

namespace WondeModels
{
    //using Microsoft.AspNetCore.Http.HttpResults;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.Text.RegularExpressions;

    public partial class WondeStudent
    {
        [JsonProperty("data")]
        public List<WondeStudent_obj> data { get; set; }

        [JsonProperty("meta")]
        public WondeStudent_Meta meta { get; set; }
    }

    public partial class WondeStudent_obj
    {
        [JsonProperty("id")]
        public string id { get; set; }

        [JsonProperty("upi")]
        public string upi { get; set; }

        [JsonProperty("mis_id")]
        public string mis_id { get; set; }

        [JsonProperty("initials")]
        public string initials { get; set; }

        [JsonProperty("title")]
        public string title { get; set; }

        [JsonProperty("surname")]
        public string surname { get; set; }

        [JsonProperty("forename")]
        public string forename { get; set; }

        [JsonProperty("middle_names")]
        public string middle_names { get; set; }

        [JsonProperty("legal_surname")]
        public string legal_surname { get; set; }

        [JsonProperty("legal_forename")]
        public string legal_forename { get; set; }

        [JsonProperty("gender")]
        public string gender { get; set; }

        [JsonProperty("gender_identity")]
        public string gender_identity { get; set; }

        [JsonProperty("date_of_birth")]
        public WondeStudent_CreatedAt date_of_birth { get; set; }

        [JsonProperty("restored_at")]
        public WondeStudent_CreatedAt restored_at { get; set; }

        [JsonProperty("created_at")]
        public WondeStudent_CreatedAt created_at { get; set; }

        [JsonProperty("updated_at")]
        public WondeStudent_CreatedAt updated_at { get; set; }

        [JsonProperty("education_details")]
        public WondeStudent_EducationDetails education_details { get; set; }

        [JsonProperty("extended_details")]
        public WondeStudent_ExtendedDetails extended_details { get; set; }

        [JsonProperty("groups")]
        public WondeStudent_Groups groups { get; set; }

        [JsonProperty("sen_needs")]
        public WondeStudent_SenNeeds sen_needs { get; set; }
    }


    public partial class WondeStudent_Groups
    {
        [JsonProperty("data")]
        public List<WondeStudent_GroupsDatum> data { get; set; }
    }
    public partial class WondeStudent_GroupsDatum
    {
        [JsonProperty("id")]
        public string id { get; set; }

        [JsonProperty("mis_id")]
        public string mis_id { get; set; }

        [JsonProperty("name")]
        public string name { get; set; }

        [JsonProperty("code")]
        public string code { get; set; }

        [JsonProperty("type")]
        public string type { get; set; }

        [JsonProperty("description")]
        public string description { get; set; }

        [JsonProperty("notes")]
        public string notes { get; set; }

        [JsonProperty("division")]
        public string division { get; set; }

        [JsonProperty("restored_at")]
        public WondeStudent_CreatedAt restored_at { get; set; }

        [JsonProperty("created_at")]
        public WondeStudent_CreatedAt created_at { get; set; }

        [JsonProperty("updated_at")]
        public WondeStudent_CreatedAt updated_at { get; set; }

        [JsonProperty("meta")]
        public DatumMeta meta { get; set; }
    }
    public partial class DatumMeta
    {
        [JsonProperty("start_date")]
        public WondeStudent_CreatedAt start_date { get; set; }

        [JsonProperty("end_date")]
        public WondeStudent_CreatedAt end_date { get; set; }
    }
    public partial class WondeStudent_CreatedAt
    {
        [JsonProperty("date")]
        public DateTime date { get; set; }

        [JsonProperty("timezone_type")]
        public long timezone_type { get; set; }

        [JsonProperty("timezone")]
        public string timezone { get; set; }
    }

    public partial class WondeStudent_EducationDetails
    {
        [JsonProperty("data")]
        public WondeStudent_EducationDetailsData data { get; set; }
    }

    public partial class WondeStudent_EducationDetailsData
    {
        [JsonProperty("admission_number")]
        public string admission_number { get; set; }

        [JsonProperty("upn")]
        public string upn { get; set; }

        [JsonProperty("local_upn")]
        public string local_upn { get; set; }

        [JsonProperty("former_upn")]
        public string former_upn { get; set; }

        [JsonProperty("learner_number")]
        public string learner_number { get; set; }

        [JsonProperty("current_nc_year")]
        public string current_nc_year { get; set; }

        [JsonProperty("part_time")]
        public string part_time { get; set; }

        [JsonProperty("part_time_rate")]
        public string part_time_rate { get; set; }

        [JsonProperty("admission_date")]
        public WondeStudent_CreatedAt admission_date { get; set; }

        [JsonProperty("leaving_date")]
        public WondeStudent_CreatedAt leaving_date { get; set; }
    }

    public partial class WondeStudent_ExtendedDetails
    {
        [JsonProperty("data")]
        public WondeStudent_ExtendedDetailsData data { get; set; }
    }

    public partial class WondeStudent_ExtendedDetailsData
    {
        [JsonProperty("next_of_kin")]
        public string next_of_kin { get; set; }

        [JsonProperty("religion")]
        public string religion { get; set; }

        [JsonProperty("ethnicity")]
        public string ethnicity { get; set; }

        [JsonProperty("ethnicity_code")]
        public string ethnicity_code { get; set; }

        [JsonProperty("nationality")]
        public string nationality { get; set; }

        [JsonProperty("birth_place")]
        public string birth_place { get; set; }

        [JsonProperty("custody_alert")]
        public string custody_alert { get; set; }

        [JsonProperty("custody_details")]
        public string custody_details { get; set; }

        [JsonProperty("dietary_needs")]
        public string dietary_needs { get; set; }

        [JsonProperty("paramedical_support")]
        public string paramedical_support { get; set; }

        [JsonProperty("sen_status")]
        public string sen_status { get; set; }

        [JsonProperty("first_language")]
        public string first_language { get; set; }

        [JsonProperty("marital_status")]
        public string marital_status { get; set; }

        [JsonProperty("in_lea_care")]
        public bool? in_lea_care { get; set; }

        [JsonProperty("ever_in_care")]
        public bool? ever_in_care { get; set; }

        [JsonProperty("free_school_meals")]
        public bool? free_school_meals { get; set; }

        [JsonProperty("free_school_meals_6")]
        public bool? free_school_meals_6 { get; set; }

        [JsonProperty("english_as_additional_language")]
        public bool? english_as_additional_language { get; set; }

        [JsonProperty("english_as_additional_language_status")]
        public string english_as_additional_language_status { get; set; }

        [JsonProperty("premium_pupil_indicator")]
        public bool? premium_pupil_indicator { get; set; }

        [JsonProperty("premium_pupil_eligible")]
        public bool? premium_pupil_eligible { get; set; }

        [JsonProperty("premium_pupil_notes")]
        public string premium_pupil_notes { get; set; }

        [JsonProperty("service_children_indicator")]
        public bool? service_children_indicator { get; set; }

        [JsonProperty("enrolment_status")]
        public string enrolment_status { get; set; }

        [JsonProperty("enrolment_start_date")]
        public WondeStudent_CreatedAt enrolment_start_date { get; set; }

        [JsonProperty("enrolment_end_date")]
        public WondeStudent_CreatedAt enrolment_end_date { get; set; }

        [JsonProperty("gifted_and_talented_status")]
        public bool? gifted_and_talented_status { get; set; }

        [JsonProperty("national_insurance_number")]
        public string national_insurance_number { get; set; }

        [JsonProperty("application_status")]
        public string application_status { get; set; }

        [JsonProperty("boarding_status")]
        public string boarding_status { get; set; }

        [JsonProperty("permanent_resident")]
        public string permanent_resident { get; set; }

        [JsonProperty("in_care_details")]
        public string in_care_details { get; set; }

        [JsonProperty("general_notes")]
        public string general_notes { get; set; }

        [JsonProperty("leaver_destination")]
        public string leaver_destination { get; set; }

        [JsonProperty("fsm_review_date")]
        public string fsm_review_date { get; set; }

        [JsonProperty("youth_support_services_agreement")]
        public string youth_support_services_agreement { get; set; }

        [JsonProperty("responsible_care_authority")]
        public string responsible_care_authority { get; set; }

        [JsonProperty("home_language")]
        public string home_language { get; set; }

        [JsonProperty("child_protection_plan")]
        public bool? child_protection_plan { get; set; }

        [JsonProperty("child_in_need")]
        public bool? child_in_need { get; set; }
    }


    public partial class WondeStudent_SenNeeds
    {
        [JsonProperty("data")]
        public List<WondeStudent_SenNeedsDatum> data { get; set; }
    }

    public partial class WondeStudent_SenNeedsDatum
    {
        [JsonProperty("id")]
        public string id { get; set; }

        [JsonProperty("description")]
        public string description { get; set; }

        [JsonProperty("rank")]
        public int? rank { get; set; }

        [JsonProperty("category_code")]
        public string category_code { get; set; }

        [JsonProperty("category_description")]
        public string category_description { get; set; }

        [JsonProperty("type_code")]
        public string type_code { get; set; }

        [JsonProperty("type_description")]
        public string type_description { get; set; }

        [JsonProperty("start_date")]
        public WondeStudent_CreatedAt start_date { get; set; }

        [JsonProperty("end_date")]
        public WondeStudent_CreatedAt end_date { get; set; }

        [JsonProperty("created_at")]
        public WondeStudent_CreatedAt created_at { get; set; }

        [JsonProperty("updated_at")]
        public WondeStudent_CreatedAt updated_at { get; set; }
    }

    public partial class WondeStudent_Meta
    {
        [JsonProperty("pagination")]
        public WondeStudent_Pagination pagination { get; set; }

        [JsonProperty("includes")]
        public List<string> includes { get; set; }
    }

    public partial class WondeStudent_Pagination
    {
        [JsonProperty("next")]
        public Uri next { get; set; }

        [JsonProperty("previous")]
        public object previous { get; set; }

        [JsonProperty("more")]
        public bool more { get; set; }

        [JsonProperty("per_page")]
        public long per_page { get; set; }

        [JsonProperty("current_page")]
        public long current_page { get; set; }
    }

    public partial class WondeStudent
    {
        public static WondeStudent FromJson(string json) => JsonConvert.DeserializeObject<WondeStudent>(json, WondeModels.WondeStudent_Converter.Settings);
    }

    public static class WondeStudent_Serialize
    {
        public static string ToJson(this WondeStudent self) => JsonConvert.SerializeObject(self, WondeModels.WondeStudent_Converter.Settings);
    }

    internal static class WondeStudent_Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
